global:
  scrape_interval: 15s

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 15s
  #   metrics_path: /prometheus/metrics
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'mcim-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']

  - job_name: localhost
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9100']